/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MemberRouteRouteImport } from './routes/member/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as MemberIndexRouteImport } from './routes/member/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AppMembersIndexRouteImport } from './routes/app/members/index'
import { Route as AppEventsIndexRouteImport } from './routes/app/events/index'
import { Route as PublicSignInIndexRouteImport } from './routes/_public/sign-in/index'
import { Route as PublicEventsIndexRouteImport } from './routes/_public/events/index'
import { Route as PublicAboutIndexRouteImport } from './routes/_public/about/index'
import { Route as AppEventsCreateRouteImport } from './routes/app/events/create'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PublicEventsEventIdRouteImport } from './routes/_public/events/$eventId'
import { Route as AppEventsEventIdIndexRouteImport } from './routes/app/events/$eventId/index'
import { Route as AppEventsEventIdEditIndexRouteImport } from './routes/app/events/$eventId/edit/index'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRouteRoute = MemberRouteRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AppMembersIndexRoute = AppMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRouteRoute,
} as any)
const PublicSignInIndexRoute = PublicSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEventsIndexRoute = PublicEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutIndexRoute = PublicAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AppEventsCreateRoute = AppEventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicEventsEventIdRoute = PublicEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AppEventsEventIdIndexRoute = AppEventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventsEventIdEditIndexRoute =
  AppEventsEventIdEditIndexRouteImport.update({
    id: '/events/$eventId/edit/',
    path: '/events/$eventId/edit/',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/member': typeof MemberRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/': typeof AppIndexRoute
  '/member/': typeof MemberIndexRoute
  '/events/$eventId': typeof PublicEventsEventIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/events/create': typeof AppEventsCreateRoute
  '/about/': typeof PublicAboutIndexRoute
  '/events/': typeof PublicEventsIndexRoute
  '/sign-in/': typeof PublicSignInIndexRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/app/members/': typeof AppMembersIndexRoute
  '/app/events/$eventId/': typeof AppEventsEventIdIndexRoute
  '/app/events/$eventId/edit/': typeof AppEventsEventIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/': typeof PublicIndexRoute
  '/app': typeof AppIndexRoute
  '/member': typeof MemberIndexRoute
  '/events/$eventId': typeof PublicEventsEventIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/events/create': typeof AppEventsCreateRoute
  '/about': typeof PublicAboutIndexRoute
  '/events': typeof PublicEventsIndexRoute
  '/sign-in': typeof PublicSignInIndexRoute
  '/app/events': typeof AppEventsIndexRoute
  '/app/members': typeof AppMembersIndexRoute
  '/app/events/$eventId': typeof AppEventsEventIdIndexRoute
  '/app/events/$eventId/edit': typeof AppEventsEventIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/member': typeof MemberRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_public/': typeof PublicIndexRoute
  '/app/': typeof AppIndexRoute
  '/member/': typeof MemberIndexRoute
  '/_public/events/$eventId': typeof PublicEventsEventIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/events/create': typeof AppEventsCreateRoute
  '/_public/about/': typeof PublicAboutIndexRoute
  '/_public/events/': typeof PublicEventsIndexRoute
  '/_public/sign-in/': typeof PublicSignInIndexRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/app/members/': typeof AppMembersIndexRoute
  '/app/events/$eventId/': typeof AppEventsEventIdIndexRoute
  '/app/events/$eventId/edit/': typeof AppEventsEventIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/member'
    | '/dashboard'
    | '/unauthorized'
    | '/app/'
    | '/member/'
    | '/events/$eventId'
    | '/api/auth/$'
    | '/app/events/create'
    | '/about/'
    | '/events/'
    | '/sign-in/'
    | '/app/events/'
    | '/app/members/'
    | '/app/events/$eventId/'
    | '/app/events/$eventId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/unauthorized'
    | '/'
    | '/app'
    | '/member'
    | '/events/$eventId'
    | '/api/auth/$'
    | '/app/events/create'
    | '/about'
    | '/events'
    | '/sign-in'
    | '/app/events'
    | '/app/members'
    | '/app/events/$eventId'
    | '/app/events/$eventId/edit'
  id:
    | '__root__'
    | '/_public'
    | '/app'
    | '/member'
    | '/dashboard'
    | '/unauthorized'
    | '/_public/'
    | '/app/'
    | '/member/'
    | '/_public/events/$eventId'
    | '/api/auth/$'
    | '/app/events/create'
    | '/_public/about/'
    | '/_public/events/'
    | '/_public/sign-in/'
    | '/app/events/'
    | '/app/members/'
    | '/app/events/$eventId/'
    | '/app/events/$eventId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  MemberRouteRoute: typeof MemberRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/': {
      id: '/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/app/members/': {
      id: '/app/members/'
      path: '/members'
      fullPath: '/app/members/'
      preLoaderRoute: typeof AppMembersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/events/': {
      id: '/app/events/'
      path: '/events'
      fullPath: '/app/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_public/sign-in/': {
      id: '/_public/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof PublicSignInIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/events/': {
      id: '/_public/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof PublicEventsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about/': {
      id: '/_public/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof PublicAboutIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/app/events/create': {
      id: '/app/events/create'
      path: '/events/create'
      fullPath: '/app/events/create'
      preLoaderRoute: typeof AppEventsCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/events/$eventId': {
      id: '/_public/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof PublicEventsEventIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/app/events/$eventId/': {
      id: '/app/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/app/events/$eventId/'
      preLoaderRoute: typeof AppEventsEventIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/events/$eventId/edit/': {
      id: '/app/events/$eventId/edit/'
      path: '/events/$eventId/edit'
      fullPath: '/app/events/$eventId/edit/'
      preLoaderRoute: typeof AppEventsEventIdEditIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicEventsEventIdRoute: typeof PublicEventsEventIdRoute
  PublicAboutIndexRoute: typeof PublicAboutIndexRoute
  PublicEventsIndexRoute: typeof PublicEventsIndexRoute
  PublicSignInIndexRoute: typeof PublicSignInIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicEventsEventIdRoute: PublicEventsEventIdRoute,
  PublicAboutIndexRoute: PublicAboutIndexRoute,
  PublicEventsIndexRoute: PublicEventsIndexRoute,
  PublicSignInIndexRoute: PublicSignInIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppEventsCreateRoute: typeof AppEventsCreateRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppMembersIndexRoute: typeof AppMembersIndexRoute
  AppEventsEventIdIndexRoute: typeof AppEventsEventIdIndexRoute
  AppEventsEventIdEditIndexRoute: typeof AppEventsEventIdEditIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppEventsCreateRoute: AppEventsCreateRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppMembersIndexRoute: AppMembersIndexRoute,
  AppEventsEventIdIndexRoute: AppEventsEventIdIndexRoute,
  AppEventsEventIdEditIndexRoute: AppEventsEventIdEditIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface MemberRouteRouteChildren {
  MemberIndexRoute: typeof MemberIndexRoute
}

const MemberRouteRouteChildren: MemberRouteRouteChildren = {
  MemberIndexRoute: MemberIndexRoute,
}

const MemberRouteRouteWithChildren = MemberRouteRoute._addFileChildren(
  MemberRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  MemberRouteRoute: MemberRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
